version: "3"
   
services:
  nginx:
    depends_on:
      - daphne
    image: nginx
    ports:
      - '443:443'
    volumes:
      - './files/nginx/templates:/etc/nginx/templates'
      - './files/ssl:/etc/ssl/numbas'
      - numbas:/srv
  redis:
    expose:
      - "6379"
    image: redis
    volumes:
      - redis:/data
  postgres:
    env_file:
      - 'settings.env'
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: numbas_lti
      POSTGRES_USER: numbas_lti
    expose:
      - "5432"
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  numbas-setup:
    build: .
    command: /entrypoint.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - 'settings.env'
    volumes:
      - numbas:/srv
    working_dir: /srv/numbas-lti-provider/
  workers:
    build: .
    command: /usr/local/bin/python /srv/numbas-lti-provider/manage.py runworker
    depends_on:
      - numbas-setup 
    env_file:
      - 'settings.env'
    environment:
      - DJANGO_SETTINGS_MODULE=numbasltiprovider.settings
    user: www-data
    volumes:
      - numbas:/srv
    working_dir: /srv/numbas-lti-provider/
  daphne:
    build: . 
    command: /usr/local/bin/daphne numbasltiprovider.asgi:channel_layer --port 8700 --bind 0.0.0.0 -v 2
    depends_on:
      - numbas-setup
    environment:
      - DJANGO_SETTINGS_MODULE=numbasltiprovider.settings
    expose:
      - "8700"
    restart: always 
    user: www-data
    volumes:
      - numbas:/srv
    working_dir: /srv/numbas-lti-provider/
  huey:
    build: .
    command: /usr/local/bin/python /srv/numbas-lti-provider/manage.py run_huey
    depends_on:
      - numbas-setup
    environment:
      - DJANGO_SETTINGS_MODULE=numbasltiprovider.settings
    restart: always 
    user: www-data
    volumes:
      - numbas:/srv
    working_dir: /srv/numbas-lti-provider/
volumes: 
  pgdata:
  numbas:
  redis:
