version: "3"
   
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - './files/nginx/templates:/etc/nginx/templates'
      - './files/ssl:/etc/ssl/numbas'
      - numbas:/srv
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  db:
    env_file:
      - 'settings.env'
      - 'files/postgres.env'
    environment:
      PGDATA: /var/lib/postgresql/data
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  numbas:
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - 'settings.env'
      - 'files/postgres.env'
    ports:
      - "8000:8000"
    volumes:
      - numbas:/srv
volumes: 
  pgdata:
  numbas:
  redis:
